### ISSUE TITLE
Error Loading Playlists if User has Playlists with nothing in them.

### ISSUE THREAD

**Issue by lunagloaming** [brentvollebregt/emotionify#16]
A few days ago Spotify made a breaking change to their API.  I noticed this in my own development where the request for the user's playlists with a limit of zero began to fail.  (I requested with a limit of zero to get the number of playlists without fetching any playlists).

It appears other changes may have occurred as well.  Today I encountered an issue where Emotionify would not load if I had a playlist containing zero entries.  Deleting the offending playlist allowed Emotionify to work.

This is just a preliminary report, I haven't done further research yet.  Will comment if I discover anything more.

**Comment by brentvollebregt** [comment]
Thanks for the heads up! I have been able to reproduce.

**Comment by brentvollebregt** [comment]
I've fixed the main issue, so will close this for now. Feel free to comment here or open a new issue if there is someone else specific you find 😃
